"""empty message

Revision ID: efc2691d78f8
Revises: 4cc990ca0b35
Create Date: 2021-06-28 19:38:39.438873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc2691d78f8'
down_revision = '4cc990ca0b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('currency_in_use', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'currency_in_use')
    op.drop_column('user', 'date_of_birth')
    # ### end Alembic commands ###
